### ISSUE TITLE
Is configuring a "persistent" partition (or a specific MBR slot) supported?

### ISSUE THREAD

**Issue by lah7** [boeckmann/ranish#2]
Hello! I have a retro PC with many OSes currently set up under Ranish Partition Manager 2.44. There's a _"persistent"_ FAT-32 LBA partition in **slot 2** that is shared across every operating system for data. With the old Ranish and its bootloader, selecting a partition updates **slot 1** and the active partition and leaves slot 2, 3, 4 intact - works well!

I'm considering a switch to this fork for the improved **Advanced Boot Manager** features.  I'm a bit stumped on how to configure a partition to be always visible on the same disk.

For testing, I've cloned the PC's disk into VirtualBox. I see that FAT32 LBA isn't supported past cylinder 1024 (#1) at the moment, so I'm playing around with a smaller FAT16 one. From the documentation, I'm trying to figure if this use case is possible?

This section of the documentation is a bit confusing to me. Is it related?

>  Which partitions show together with the bootable partition.
    The choices are: Last, Previous, Next, and Last3 partitions,
    including the one from which you boot.

If it helps, for reference, these are the partitions in the original Ranish **before** and **after** setting them up again to this fork:

| Ranish (2.44) | This fork (2.90.15) |
| --- | --- |
![orig](https://github.com/boeckmann/ranish/assets/13032135/a780f4fd-13ca-4a1f-ad0a-aee1e9c20eca) | ![fork](https://github.com/boeckmann/ranish/assets/13032135/d7109304-699f-4eac-becb-831592d27a85) |
| "Boot Manager" in slot 4 will be obsolete in the fork, as it sets up its own.

Thank you for working on this fork, it's really nice for the possibility to have a customisable boot menu and improved partition information!

**Comment by boeckmann** [comment]
Hello Luke, I see that the drive you are using is larger than 1024 cylinders. I have not yet extended the advanced boot loader to support "large" disks (issue #1) . Trying to use it on disks >1024 cylinders will likely result in a broken partition table if RANISH has to write a partition table entry with cylinder >1023. In your case the FAT-32 partition used as common data partition would brake it.

So for the time being recommend to stick to your version 2.44. Regarding your partition layout: you may consider to change the FAT-16 partition type to non-LBA for the partitions withing the first 1024 cylinders, for compatibility reasons.

**Comment by boeckmann** [comment]
You may setup a common data partition by defining it as the last partition and choose "Last" like in the screenshot I provided. This partition is then included in the generated partition table while booting. Please make sure that "Ignore unused part" should be set to yes!

![VirtualBox_Multiple_OSes_30_03_2024_11_25_36](https://github.com/boeckmann/ranish/assets/6333969/17d1ab83-ee03-40e2-834c-186c921bcf44)

**Comment by boeckmann** [comment]
In my case the boot menu looks like below. All systems have a common FAT-16 data partition. Tip: In the boot loader, you may press "A" after selecting a menu entry. The system is then booted from floppy after the selected partition is activated (useful to install operating systems).

![VirtualBox_Multiple_OSes_30_03_2024_11_31_04](https://github.com/boeckmann/ranish/assets/6333969/9cd123a8-b1ed-4a56-b6aa-7ee84931db9b)

**Comment by lah7** [comment]
Thank you for your quick response and tips! 

All makes perfect sense. I misread the LBA _disk_ limitations (#1), overlooked cylinders and focused on it being a 'LBA' partition 😁  My bad! The software allowed configuration beyond cylinder 1024, so I might had been too hopeful.  This also explains why the NTFS partitions didn't boot.

As feedback - my disk clone was actually an old copy. The real computer's disk [actually has a Linux ext4 partition](https://github.com/boeckmann/ranish/assets/13032135/0b7523a6-b202-41e5-8849-06461bf8804c) after the data one. At some point I'd shrunk the data partition to make room for another OS! If this version could offer similar functionality to the original by specifying `#8` (as `slot 2`) instead of `Last`, which would greatly help this scenario! That said, there is `Last3` option which in theory should work.

For now, I'll keep the original system under the old Ranish and look forward to future updates. Thanks again!
